import type { PhilosophyKey } from "./quiz-content";
import type { Profile } from "./profiles-zh";

export const enProfiles: Record<PhilosophyKey, Profile> = {
  existentialism: {
    name: "Existentialism", english: "EXISTENTIALISM", sigil: "Blade of Freedom",
    motto: "The world wrote no answer for you, so you take up the pen.",
    description: "You do not wait for the universe to grant you meaning. We exist first, then become ourselves through choice, responsibility, and creation. Freedom is not weightless, but you would rather carry it than hand your life to a ready-made script.",
    light: "Authentic, free, willing to define yourself",
    shadow: "Every choice can begin to feel like a trial",
    coreQuestion: "Becoming myself",
    history: "Existentialism took a distinctive form in nineteenth- and twentieth-century Europe. It begins not with an abstract human essence, but with the concrete individual trying to live in a world without ready-made answers.",
    ideas: ["Existence precedes essence: we are not born with a fixed instruction manual.", "Freedom and responsibility are inseparable; refusing to choose is also a choice.", "Anxiety is not merely a malfunction—it often appears when we realise that we are free to choose."],
    misconception: "It is neither selfishness nor simple pessimism. Existentialism asks us to choose authentically and to accept how our choices affect others.",
    thinkers: "Søren Kierkegaard, Friedrich Nietzsche, Jean-Paul Sartre, Simone de Beauvoir",
    reflection: "If no role defined you in advance, how would you choose to become yourself?",
  },
  absurdism: {
    name: "Absurdism", english: "ABSURDISM", sigil: "Fire of Revolt",
    motto: "The universe is silent; I still answer with fire.",
    description: "You see the fracture between our hunger for meaning and a world that refuses to reply. You neither escape into false certainty nor surrender to nothingness. You choose to live, create, love, and perhaps grin at the abyss.",
    light: "Lucid, resilient, rebellious with humour",
    shadow: "May hide real exhaustion behind irony",
    coreQuestion: "Burning within the silence",
    history: "Absurdism explores the conflict between the human demand for meaning and the silence of the universe. Albert Camus called this unresolved tension “the absurd.”",
    ideas: ["Human beings seek definite meaning, while the world promises no answer.", "Escape, false certainty, and total surrender are not the only responses.", "Living, experiencing, and creating with open eyes is itself a revolt."],
    misconception: "Absurdism does not mean that nothing matters. It asks us to live seriously even without an ultimate guarantee.",
    thinkers: "Albert Camus; often read alongside the literary worlds of Kafka and Dostoevsky",
    reflection: "If the world gives no answer, what would you still choose to love fiercely?",
  },
  stoicism: {
    name: "Stoicism", english: "STOICISM", sigil: "Silent Ring",
    motto: "I do not command the storm, but the hand on the helm is mine.",
    description: "You divide confusion into what can be changed and what must be accepted. Dignity comes from judgment and action rather than applause. Restraint is not coldness, but a way to keep the world from invading your inner centre.",
    light: "Steady, self-possessed, clear in action",
    shadow: "May flatten feelings before they have been fully felt",
    coreQuestion: "Guarding inner order",
    history: "Stoicism began in ancient Greece and flourished in Rome. It is a practical philosophy of judgment, virtue, emotion, and action.",
    ideas: ["Distinguish your judgments and actions from outcomes and other people.", "Character and virtue matter more than fame, wealth, or luck.", "Emotions should be understood and recalibrated, not brutally erased."],
    misconception: "Stoicism is not indifference or passive endurance; it demands courageous action where action is possible.",
    thinkers: "Zeno, Epictetus, Seneca, Marcus Aurelius",
    reflection: "What deserves your action today, and what can you stop trying to control?",
  },
  epicureanism: {
    name: "Epicureanism", english: "EPICUREANISM", sigil: "Laurel Garden",
    motto: "Happiness is not a feast, but freedom from being chased by lack.",
    description: "You believe a good life need not be grand. Friendship, tranquility, freedom from bodily pain, and a wise understanding of desire are already precious. You seek not excess, but relief from endless craving.",
    light: "Sensitive, content, attentive to real pleasure",
    shadow: "May avoid necessary risks to preserve peace",
    coreQuestion: "Letting the mind grow quiet",
    history: "Epicurus founded the Garden in ancient Greece and taught that understanding desire, nature, and death can lead to calm and lucid pleasure.",
    ideas: ["Pleasure begins with less bodily pain and less fear in the mind.", "Separate natural, necessary desires from cravings enlarged by society.", "Friendship, moderation, and reflection are more dependable than luxury."],
    misconception: "Epicureanism is not indulgence. Its pleasure is simple, stable, and free from the feeling of lack.",
    thinkers: "Epicurus, Lucretius",
    reflection: "Once comparison and performance disappear, what still truly satisfies you?",
  },
  humanism: {
    name: "Humanism", english: "HUMANISM", sigil: "Light of Resonance",
    motto: "Even without revelation, every person deserves to be taken seriously.",
    description: "You place dignity, compassion, reason, and creativity at the centre. Meaning need not arrive from a cosmic scale; it can emerge when people recognise one another, share knowledge, and reduce suffering. Civilisation is a work we maintain together.",
    light: "Compassionate, responsible, committed to shared progress",
    shadow: "May carry too much disappointment on behalf of humanity",
    coreQuestion: "Making the world more like a home",
    history: "Humanism gained an influential form during the Renaissance and later developed into secular and religious traditions. They share a concern for dignity, education, agency, and human potential.",
    ideas: ["People possess subjectivity and capacities worthy of respect.", "Ethics can grow from compassion, reason, experience, and shared life.", "Knowledge, art, and institutions should help people live more fully."],
    misconception: "Humanism does not claim that humans are always right, nor does it ignore nature. It asks humanity to take responsibility for its power.",
    thinkers: "Erasmus, Pico della Mirandola, and modern secular humanist traditions",
    reflection: "Whose life do you hope will become more dignified because you existed?",
  },
  skepticism: {
    name: "Skepticism", english: "SKEPTICISM", sigil: "Eye in the Mist",
    motto: "I do not rush to believe, and I do not rush to deny.",
    description: "You keep a measured distance from beautiful, certain answers. You care how a conclusion is justified, what language conceals, and where you may be wrong. Suspending judgment is not weakness, but a way of protecting truth.",
    light: "Perceptive, independent, difficult to manipulate",
    shadow: "May keep dismantling until nowhere feels solid",
    coreQuestion: "Distinguishing truth from illusion",
    history: "Skepticism reaches back to Pyrrhonism and Academic skepticism in ancient Greece, and later became central to modern science and epistemology.",
    ideas: ["Perception, language, and reasoning can all fail.", "When evidence is insufficient, withholding judgment is more honest than certainty.", "Skepticism must also question itself or it becomes another dogma."],
    misconception: "Skepticism does not reject every belief; it matches the strength of belief to the strength of evidence.",
    thinkers: "Pyrrho, Sextus Empiricus, David Hume",
    reflection: "What evidence would change the belief of which you are most certain?",
  },
  idealism: {
    name: "Idealism", english: "IDEALISM", sigil: "Crystal of Mind",
    motto: "Perhaps the deepest substance of the world has always been mind.",
    description: "You suspect consciousness is not an accidental bubble rising from matter. Experience, ideas, and perception may be closer to the centre of existence than supposedly objective things. You take dreams, symbols, and subjectivity seriously.",
    light: "Imaginative, spiritually deep, richly perceptive",
    shadow: "May let an enchanting explanation outrun its evidence",
    coreQuestion: "Understanding consciousness itself",
    history: "Philosophical idealism includes many positions, united by the view that mind, ideas, or experience are fundamental to understanding reality.",
    ideas: ["We encounter the world through consciousness, concepts, and perception.", "Reality may not be reducible to mind-independent matter alone.", "Different idealisms disagree about whether a world exists independently of experience."],
    misconception: "Idealism is not “thoughts make things happen.” It asks how reality becomes a world that can be experienced.",
    thinkers: "Plato, George Berkeley, Immanuel Kant, G. W. F. Hegel",
    reflection: "When you say “reality,” how much comes from the world and how much from the way you perceive it?",
  },
  naturalism: {
    name: "Naturalism", english: "NATURALISM", sigil: "Bones of the Stars",
    motto: "We belong to the universe; we are not its exception.",
    description: "You find the natural world wondrous enough without adding a supernatural layer. Consciousness, love, and civilisation can be precious while still arising through matter, evolution, and causality. Mechanism does not destroy poetry; it sharpens awe.",
    light: "Truth-seeking, clear, respectful of evidence",
    shadow: "May underestimate what subjective experience cannot quantify",
    coreQuestion: "Seeing how the world works",
    history: "Naturalism holds that the world can be understood through natural causes and empirical inquiry without requiring supernatural entities.",
    ideas: ["Humanity and consciousness are parts of nature, not exceptions outside it.", "Knowledge should remain answerable to observable evidence and reliable methods.", "Natural explanation does not automatically erase value, emotion, or art."],
    misconception: "Naturalism does not say only cold matter matters; it says precious things can be fully real within nature.",
    thinkers: "David Hume, John Dewey, and contemporary scientific naturalism",
    reflection: "If understanding a mechanism does not destroy its poetry, what would you most like to understand?",
  },
  determinism: {
    name: "Determinism", english: "DETERMINISM", sigil: "Chain of Causes",
    motto: "Every star’s path begins in older stardust.",
    description: "You notice the genes, experiences, environments, and physical causes behind each choice. Free will may be less independent than people imagine. Understanding constraints does not end action; it reduces blame and directs attention toward changing conditions.",
    light: "Causally perceptive, less morally arrogant",
    shadow: "May mistake an unfinished future for a fixed one",
    coreQuestion: "Understanding the forces that shape me",
    history: "Determinism holds that events are shaped by prior conditions and laws. It spans metaphysics, physics, psychology, and debates over free will.",
    ideas: ["Choices are deeply influenced by biology, environment, experience, and present state.", "Causation is not fatalism; knowing causes can change later conditions.", "Compatibilism argues that meaningful freedom can coexist with causation."],
    misconception: "Determinism does not mean effort is useless. Effort itself can be a cause that changes the future.",
    thinkers: "Baruch Spinoza, Pierre-Simon Laplace; modern compatibilist Daniel Dennett",
    reflection: "What forces shaped you, and what new causes can you introduce into the future?",
  },
  nihilism: {
    name: "Nihilism", english: "NIHILISM", sigil: "Obsidian Crown",
    motto: "When inherited values collapse, the night does not lie to you.",
    description: "You see through values that habit has dressed as truth. The universe offers no obvious purpose, and morality and identity may be human constructions. Your power is honest demolition; your test is whether you will build after clearing the ground.",
    light: "Radically honest, free from false authority",
    shadow: "After dismantling everything, may forget that you can create",
    coreQuestion: "Crossing the ruins of value",
    history: "Nihilism questions whether value, knowledge, or meaning has an objective foundation. Since the nineteenth century it has named a central crisis of modernity.",
    ideas: ["Traditional values may be neither natural, eternal, nor cosmically guaranteed.", "Dismantling false authority can free us, but can also leave a vacuum.", "Nihilism can be a diagnosis—or a stage to move through."],
    misconception: "Nihilism need not mean despair or destruction. Finding no ready-made meaning is not the same as refusing to create any meaning.",
    thinkers: "Nietzsche’s diagnosis of nihilism and the Russian nihilism portrayed by Turgenev",
    reflection: "When old values no longer convince you, what will you preserve or create?",
  },
  transhumanism: {
    name: "Transhumanism", english: "TRANSHUMANISM", sigil: "Wings of the Future",
    motto: "Humanity is not a finished product, but code still being rewritten.",
    description: "You see technology as an organ through which consciousness may continue to evolve. Disease, ageing, and cognitive limits need not be romanticised as untouchable fate. You wager on a wider future while asking what “human” should still mean after the upgrade.",
    light: "Visionary, creative, unwilling to submit to limits",
    shadow: "May race toward the future and overlook people in the present",
    coreQuestion: "Crossing the boundaries of life",
    history: "Transhumanism is a modern movement that proposes using science and technology to reduce disease, ageing, and cognitive limitation while exploring possible future forms of humanity.",
    ideas: ["Biological limits need not all be treated as immutable fate.", "Enhancement must address fairness, risk, identity, and power.", "Ideas about the good life should guide technological progress."],
    misconception: "It is not simply “becoming a robot,” nor does it assume every new technology should be adopted.",
    thinkers: "Julian Huxley, Nick Bostrom, and contemporary bioethics and futures studies",
    reflection: "If you could upgrade yourself, what would you change—and what would you refuse to lose?",
  },
  simulationism: {
    name: "Simulation Hypothesis", english: "SIMULATION HYPOTHESIS", sigil: "Mirror Matrix",
    motto: "Reality may be an interface, yet experience still happens.",
    description: "You remain radically open about reality’s foundations. Mathematical order, information, and simulation may help explain a strangely precise universe. You are drawn to observers beyond the boundary, while remembering that possibility is not proof.",
    light: "Open, systemic, willing to ask ultimate questions",
    shadow: "May use an unfalsifiable possibility as an escape",
    coreQuestion: "Touching reality’s underlying layer",
    history: "The simulation hypothesis is a contemporary metaphysical proposal that experienced reality may be generated by a deeper informational or computational process. It is not established science.",
    ideas: ["Could an advanced civilisation run simulations containing conscious subjects?", "Rules inside a simulation would still constitute reality for internal observers.", "The proposal faces problems of testability and infinite regress."],
    misconception: "It is not a fact, and mystery alone does not prove it. For now it is best treated as philosophical speculation.",
    thinkers: "Nick Bostrom’s simulation argument; related work in philosophy of information and digital physics",
    reflection: "Even if reality is an interface, what would still carry genuine weight in your life?",
  },
};

export const frProfiles: Record<PhilosophyKey, Profile> = {
  existentialism: {
    name: "Existentialisme", english: "EXISTENTIALISM", sigil: "Lame de liberté",
    motto: "Le monde n’a écrit aucune réponse pour vous ; vous prenez donc la plume.",
    description: "Vous n’attendez pas que l’univers vous accorde un sens. Nous existons d’abord, puis devenons nous-mêmes par nos choix, nos responsabilités et nos créations. La liberté pèse, mais vous préférez la porter plutôt que remettre votre vie à un scénario tout fait.",
    light: "Authentique, libre, capable de vous définir",
    shadow: "Chaque choix peut finir par ressembler à un jugement",
    coreQuestion: "Devenir moi-même",
    history: "L’existentialisme prend une forme marquante dans l’Europe des XIXe et XXe siècles. Il ne part pas d’une essence humaine abstraite, mais de l’individu concret qui cherche à vivre sans réponse préparée.",
    ideas: ["L’existence précède l’essence : personne ne naît avec un mode d’emploi définitif.", "Liberté et responsabilité sont liées ; ne pas choisir est encore un choix.", "L’angoisse apparaît souvent lorsque nous prenons conscience de notre liberté."],
    misconception: "Ce n’est ni de l’égoïsme ni un simple pessimisme. L’existentialisme demande de choisir authentiquement et d’assumer l’effet de nos choix sur autrui.",
    thinkers: "Søren Kierkegaard, Friedrich Nietzsche, Jean-Paul Sartre, Simone de Beauvoir",
    reflection: "Si aucun rôle ne vous définissait, comment choisiriez-vous de devenir vous-même ?",
  },
  absurdism: {
    name: "Absurdisme", english: "ABSURDISM", sigil: "Feu de la révolte",
    motto: "L’univers se tait ; je lui réponds pourtant avec ferveur.",
    description: "Vous voyez la fracture entre notre soif de sens et un monde qui refuse de répondre. Vous ne fuyez ni dans une fausse certitude ni dans le néant. Vous choisissez de vivre, de créer, d’aimer, et peut-être de sourire à l’abîme.",
    light: "Lucide, résilient, rebelle avec humour",
    shadow: "Peut cacher une fatigue réelle derrière l’ironie",
    coreQuestion: "Brûler dans le silence",
    history: "L’absurdisme explore le conflit entre l’exigence humaine de sens et le silence de l’univers. Albert Camus appelle cette tension impossible à abolir « l’absurde ».",
    ideas: ["L’être humain cherche un sens certain, mais le monde ne promet aucune réponse.", "La fuite, la fausse certitude et l’abandon ne sont pas les seules issues.", "Vivre, éprouver et créer lucidement constitue déjà une révolte."],
    misconception: "L’absurdisme ne signifie pas que rien ne compte. Il invite au contraire à vivre pleinement sans garantie ultime.",
    thinkers: "Albert Camus ; souvent lu avec les univers littéraires de Kafka et Dostoïevski",
    reflection: "Si le monde ne répond pas, pour quoi resteriez-vous malgré tout passionné ?",
  },
  stoicism: {
    name: "Stoïcisme", english: "STOICISM", sigil: "Anneau silencieux",
    motto: "Je ne commande pas la tempête, mais la main sur la barre est la mienne.",
    description: "Vous séparez ce qui peut être changé de ce qui doit être accepté. La dignité vient du jugement et de l’action, non des applaudissements. La maîtrise n’est pas froideur, mais protection de votre centre intérieur.",
    light: "Stable, maître de soi, clair dans l’action",
    shadow: "Peut aplatir trop tôt ce qui devait d’abord être ressenti",
    coreQuestion: "Préserver l’ordre intérieur",
    history: "Né dans la Grèce antique puis développé à Rome, le stoïcisme est une philosophie pratique du jugement, de la vertu, de l’émotion et de l’action.",
    ideas: ["Distinguer vos jugements et vos actes des résultats et des autres.", "Le caractère et la vertu comptent plus que la gloire, la richesse ou la chance.", "Les émotions doivent être comprises et ajustées, non brutalement effacées."],
    misconception: "Le stoïcisme n’est ni indifférence ni résignation ; il exige d’agir courageusement là où l’action est possible.",
    thinkers: "Zénon, Épictète, Sénèque, Marc Aurèle",
    reflection: "Qu’est-ce qui mérite votre action aujourd’hui, et que pouvez-vous cesser de vouloir contrôler ?",
  },
  epicureanism: {
    name: "Épicurisme", english: "EPICUREANISM", sigil: "Jardin de lauriers",
    motto: "Le bonheur n’est pas un banquet, mais la fin de la poursuite du manque.",
    description: "Vous pensez qu’une vie bonne n’a pas besoin d’être grandiose. L’amitié, la tranquillité, l’absence de douleur et une compréhension lucide du désir sont déjà précieuses. Vous ne cherchez pas l’excès, mais la fin de l’envie sans limite.",
    light: "Sensible, satisfait, attentif au plaisir véritable",
    shadow: "Peut éviter des risques nécessaires pour préserver la paix",
    coreQuestion: "Apaiser l’esprit",
    history: "Épicure fonda le Jardin dans la Grèce antique et enseigna que comprendre le désir, la nature et la mort permet un plaisir calme et lucide.",
    ideas: ["Le plaisir commence par moins de douleur physique et moins de peur.", "Distinguer les désirs naturels et nécessaires des envies amplifiées par la société.", "L’amitié, la modération et la réflexion sont plus sûres que le luxe."],
    misconception: "L’épicurisme n’est pas la débauche. Son plaisir est simple, stable et libéré du sentiment de manque.",
    thinkers: "Épicure, Lucrèce",
    reflection: "Sans comparaison ni mise en scène, qu’est-ce qui vous satisfait encore vraiment ?",
  },
  humanism: {
    name: "Humanisme", english: "HUMANISM", sigil: "Lumière de résonance",
    motto: "Même sans révélation, chaque personne mérite d’être prise au sérieux.",
    description: "Vous placez la dignité, la compassion, la raison et la créativité au centre. Le sens n’a pas besoin de venir du cosmos ; il peut naître lorsque les humains se reconnaissent, partagent le savoir et réduisent la souffrance. La civilisation est une œuvre commune.",
    light: "Compatissant, responsable, attaché au progrès partagé",
    shadow: "Peut porter trop de déception au nom de l’humanité",
    coreQuestion: "Faire du monde une demeure humaine",
    history: "L’humanisme prit une forme influente à la Renaissance, puis se diversifia en traditions laïques et religieuses, toutes soucieuses de dignité, d’éducation et de potentiel humain.",
    ideas: ["Chaque personne possède une subjectivité et des capacités dignes de respect.", "L’éthique peut venir de la compassion, de la raison, de l’expérience et de la vie commune.", "Le savoir, l’art et les institutions doivent aider chacun à vivre plus pleinement."],
    misconception: "L’humanisme ne dit pas que l’humain a toujours raison et n’ignore pas la nature ; il exige que l’humanité réponde de son pouvoir.",
    thinkers: "Érasme, Pic de la Mirandole et les traditions humanistes laïques modernes",
    reflection: "Quelle vie voudriez-vous rendre plus digne par le simple fait d’avoir existé ?",
  },
  skepticism: {
    name: "Scepticisme", english: "SKEPTICISM", sigil: "Œil dans la brume",
    motto: "Je ne me hâte ni de croire ni de nier.",
    description: "Vous gardez vos distances avec les réponses belles et certaines. Vous demandez comment une conclusion est justifiée, ce que le langage cache et où vous pourriez vous tromper. Suspendre son jugement protège la vérité.",
    light: "Perspicace, indépendant, difficile à manipuler",
    shadow: "Peut tout déconstruire jusqu’à ne plus trouver d’appui",
    coreQuestion: "Distinguer le vrai de l’illusion",
    history: "Le scepticisme remonte au pyrrhonisme et à la tradition académique grecque, puis devient une méthode essentielle de la science et de l’épistémologie modernes.",
    ideas: ["La perception, le langage et le raisonnement peuvent tous échouer.", "Lorsque les preuves manquent, suspendre son jugement est plus honnête.", "Le scepticisme doit aussi se questionner lui-même pour ne pas devenir un dogme."],
    misconception: "Le scepticisme ne refuse pas toute croyance ; il adapte la force de la croyance à celle des preuves.",
    thinkers: "Pyrrhon, Sextus Empiricus, David Hume",
    reflection: "Quelle preuve vous ferait changer l’opinion dont vous êtes le plus certain ?",
  },
  idealism: {
    name: "Idéalisme", english: "IDEALISM", sigil: "Cristal de l’esprit",
    motto: "Peut-être que la matière la plus profonde du monde a toujours été l’esprit.",
    description: "Vous soupçonnez que la conscience n’est pas une bulle accidentelle produite par la matière. L’expérience, les idées et la perception pourraient être plus proches du centre de l’existence que les objets prétendument objectifs.",
    light: "Imaginatif, profond, richement perceptif",
    shadow: "Peut laisser une explication séduisante devancer les preuves",
    coreQuestion: "Comprendre la conscience elle-même",
    history: "L’idéalisme philosophique rassemble plusieurs positions qui accordent à l’esprit, aux idées ou à l’expérience un rôle fondamental dans la compréhension du réel.",
    ideas: ["Nous rencontrons le monde à travers la conscience, les concepts et la perception.", "La réalité n’est peut-être pas réductible à une matière indépendante de l’esprit.", "Les idéalismes diffèrent sur l’existence d’un monde indépendant de l’expérience."],
    misconception: "L’idéalisme ne dit pas que penser suffit à faire arriver les choses ; il demande comment la réalité devient un monde vécu.",
    thinkers: "Platon, George Berkeley, Emmanuel Kant, G. W. F. Hegel",
    reflection: "Quand vous dites « réalité », quelle part vient du monde et quelle part de votre manière de percevoir ?",
  },
  naturalism: {
    name: "Naturalisme", english: "NATURALISM", sigil: "Os des étoiles",
    motto: "Nous appartenons à l’univers ; nous n’en sommes pas l’exception.",
    description: "Le monde naturel vous semble assez merveilleux sans couche surnaturelle. La conscience, l’amour et la civilisation peuvent être précieux tout en émergeant de la matière, de l’évolution et de la causalité. Le mécanisme affine l’émerveillement.",
    light: "Attaché au vrai, clair, respectueux des preuves",
    shadow: "Peut sous-estimer ce que l’expérience subjective ne quantifie pas",
    coreQuestion: "Voir comment le monde fonctionne",
    history: "Le naturalisme soutient que le monde peut être compris par les causes naturelles et l’enquête empirique, sans recourir à des entités surnaturelles.",
    ideas: ["L’humanité et la conscience appartiennent à la nature.", "Le savoir doit répondre aux preuves observables et aux méthodes fiables.", "L’explication naturelle n’efface ni la valeur, ni l’émotion, ni l’art."],
    misconception: "Le naturalisme ne dit pas que seule la matière froide importe ; il dit que les choses précieuses sont pleinement réelles dans la nature.",
    thinkers: "David Hume, John Dewey et le naturalisme scientifique contemporain",
    reflection: "Si comprendre un mécanisme n’en détruit pas la poésie, que voudriez-vous comprendre ?",
  },
  determinism: {
    name: "Déterminisme", english: "DETERMINISM", sigil: "Chaîne des causes",
    motto: "La trajectoire de chaque étoile commence dans une poussière plus ancienne.",
    description: "Vous remarquez les gènes, les expériences, les milieux et les causes physiques derrière chaque choix. Le libre arbitre est peut-être moins indépendant qu’on ne le croit. Comprendre les contraintes réduit le blâme et aide à changer les conditions.",
    light: "Lucide sur les causes, moins arrogant moralement",
    shadow: "Peut confondre un avenir inachevé avec un avenir fixé",
    coreQuestion: "Comprendre les forces qui me façonnent",
    history: "Le déterminisme affirme que les événements sont façonnés par des conditions antérieures et des lois. Il traverse la métaphysique, la physique, la psychologie et le débat sur le libre arbitre.",
    ideas: ["Les choix sont influencés par la biologie, le milieu, l’expérience et l’état présent.", "La causalité n’est pas le fatalisme : connaître les causes permet de changer les conditions.", "Le compatibilisme soutient qu’une liberté significative peut coexister avec la causalité."],
    misconception: "Le déterminisme ne signifie pas que l’effort est inutile. L’effort peut lui-même devenir une cause qui transforme l’avenir.",
    thinkers: "Baruch Spinoza, Pierre-Simon de Laplace ; Daniel Dennett pour le compatibilisme moderne",
    reflection: "Quelles forces vous ont façonné, et quelles nouvelles causes pouvez-vous introduire dans l’avenir ?",
  },
  nihilism: {
    name: "Nihilisme", english: "NIHILISM", sigil: "Couronne d’obsidienne",
    motto: "Quand les anciennes valeurs s’effondrent, la nuit ne vous ment pas.",
    description: "Vous percevez les valeurs que l’habitude a déguisées en vérités. L’univers n’offre aucun but évident, et la morale ou l’identité peuvent être des constructions humaines. Votre force est la démolition honnête ; votre épreuve est de reconstruire.",
    light: "Radicalement honnête, libéré des fausses autorités",
    shadow: "Après avoir tout démonté, peut oublier qu’il est possible de créer",
    coreQuestion: "Traverser les ruines de la valeur",
    history: "Le nihilisme demande si la valeur, le savoir ou le sens ont un fondement objectif. Depuis le XIXe siècle, il nomme une crise centrale de la modernité.",
    ideas: ["Les valeurs traditionnelles ne sont peut-être ni naturelles, ni éternelles, ni garanties par le cosmos.", "Démonter une fausse autorité peut libérer, mais aussi laisser un vide.", "Le nihilisme peut être un diagnostic ou une étape à dépasser."],
    misconception: "Le nihilisme n’implique pas nécessairement le désespoir. Ne trouver aucun sens tout fait n’est pas refuser d’en créer.",
    thinkers: "Le diagnostic de Nietzsche et le nihilisme russe décrit par Tourgueniev",
    reflection: "Lorsque les anciennes valeurs ne convainquent plus, que voulez-vous préserver ou créer ?",
  },
  transhumanism: {
    name: "Transhumanisme", english: "TRANSHUMANISM", sigil: "Ailes du futur",
    motto: "L’humanité n’est pas un produit fini, mais un code encore réécrit.",
    description: "Vous voyez la technologie comme un organe par lequel la conscience peut continuer d’évoluer. La maladie, le vieillissement et les limites cognitives n’ont pas à devenir un destin intouchable. Vous pariez sur un avenir plus vaste.",
    light: "Visionnaire, créatif, rétif aux limites",
    shadow: "Peut courir vers l’avenir et oublier les personnes présentes",
    coreQuestion: "Franchir les limites de la vie",
    history: "Le transhumanisme propose d’utiliser science et technologie pour réduire la maladie, le vieillissement et les limites cognitives, tout en explorant les formes futures de l’humanité.",
    ideas: ["Les limites biologiques ne sont pas toutes des destins immuables.", "L’augmentation doit considérer l’équité, le risque, l’identité et le pouvoir.", "Une réflexion sur la vie bonne doit guider le progrès technologique."],
    misconception: "Il ne s’agit pas seulement de « devenir un robot », ni d’accepter automatiquement chaque technologie nouvelle.",
    thinkers: "Julian Huxley, Nick Bostrom, la bioéthique et les études prospectives contemporaines",
    reflection: "Si vous pouviez vous augmenter, que changeriez-vous et que refuseriez-vous de perdre ?",
  },
  simulationism: {
    name: "Hypothèse de la simulation", english: "SIMULATION HYPOTHESIS", sigil: "Matrice miroir",
    motto: "La réalité est peut-être une interface, mais l’expérience a toujours lieu.",
    description: "Vous restez radicalement ouvert aux fondements du réel. L’ordre mathématique, l’information et la simulation pourraient éclairer un univers étrangement précis. Vous imaginez l’observateur au-delà de la frontière, sans confondre possibilité et preuve.",
    light: "Ouvert, systémique, prêt à poser les questions ultimes",
    shadow: "Peut transformer une possibilité irréfutable en échappatoire",
    coreQuestion: "Toucher la couche profonde du réel",
    history: "L’hypothèse de la simulation propose que la réalité vécue soit générée par un processus informationnel ou computationnel plus profond. Ce n’est pas une théorie scientifique établie.",
    ideas: ["Une civilisation avancée pourrait-elle simuler des sujets conscients ?", "Les règles internes constitueraient toujours le réel pour les observateurs simulés.", "L’hypothèse rencontre des problèmes de testabilité et de régression infinie."],
    misconception: "Ce n’est pas un fait, et le mystère du monde ne suffit pas à la prouver. Elle reste une spéculation philosophique.",
    thinkers: "L’argument de Nick Bostrom ; la philosophie de l’information et la physique numérique",
    reflection: "Même si la réalité est une interface, qu’est-ce qui garderait un poids véritable dans votre vie ?",
  },
};
