export type Language = "en" | "zh" | "fr";
export type CopyMode = "clear" | "academic";

export type PhilosophyKey =
  | "existentialism"
  | "absurdism"
  | "stoicism"
  | "epicureanism"
  | "humanism"
  | "skepticism"
  | "idealism"
  | "naturalism"
  | "determinism"
  | "nihilism"
  | "transhumanism"
  | "simulationism";

export const philosophyKeys: PhilosophyKey[] = [
  "existentialism", "absurdism", "stoicism", "epicureanism",
  "humanism", "skepticism", "idealism", "naturalism",
  "determinism", "nihilism", "transhumanism", "simulationism",
];

export const questionWeights: Array<Partial<Record<PhilosophyKey, number>>> = [
  { existentialism: 2, determinism: -1, humanism: 0.5 },
  { absurdism: 2, nihilism: -0.5, existentialism: 0.5 },
  { stoicism: 2, determinism: 0.5 },
  { epicureanism: 2, transhumanism: -0.5 },
  { humanism: 2, nihilism: -0.5 },
  { skepticism: 2, naturalism: 1, simulationism: -0.5 },
  { idealism: 2, naturalism: -1 },
  { naturalism: 2, idealism: -1 },
  { determinism: 2, existentialism: -1 },
  { nihilism: 2, humanism: -0.5, existentialism: 0.5 },
  { transhumanism: 2, stoicism: -0.5 },
  { simulationism: 2, naturalism: -0.5, skepticism: -0.5 },
  { existentialism: 2, stoicism: 0.5, determinism: -0.5 },
  { absurdism: 2, nihilism: -0.5 },
  { stoicism: 2, skepticism: 0.5 },
  { epicureanism: 2, transhumanism: -0.5, humanism: 0.5 },
  { humanism: 2, transhumanism: 0.5 },
  { skepticism: 2, simulationism: -0.5, idealism: 0.5 },
  { idealism: 2, naturalism: -0.5 },
  { naturalism: 2, skepticism: 1, idealism: -0.5 },
  { determinism: 2, humanism: 0.5 },
  { nihilism: 2, absurdism: 0.5, humanism: -0.5 },
  { transhumanism: 2, naturalism: 0.5 },
  { simulationism: 2, humanism: 0.5, nihilism: -0.5 },
];

type QuestionCopy = {
  constellations: string[];
  academic: string[];
  clear: string[];
};

export const questionCopy: Record<Language, QuestionCopy> = {
  en: {
    constellations: [
      "Freedom", "Absurdity", "Inner order", "Pleasure", "Dignity", "Doubt",
      "Consciousness", "Nature", "Causality", "Nothingness", "Evolution", "Reality",
      "Authenticity", "Revolt", "Boundaries", "The garden", "Community", "The unknown",
      "Dreams", "Evidence", "Trajectory", "The abyss", "The future", "The interface",
    ],
    academic: [
      "Human existence has no predetermined script; who I am is constituted through successive acts of choice.",
      "Even before an eternally silent universe, one may live lucidly, passionately, and even humorously.",
      "What ultimately matters is not the event itself, but the judgment and response I bring to it.",
      "Rather than intense stimulation, I value friendship, tranquility, and freedom from the tyranny of desire.",
      "In the absence of sacred command, human dignity and reciprocal concern remain sufficient as a point of departure for ethics.",
      "When faced with a grand explanatory system, I first ask what evidence supports it and what could falsify it.",
      "Consciousness may not be a mere by-product of matter; it may be among reality’s fundamental constituents.",
      "However mysterious love, spirituality, and art appear, they still unfold within one natural world.",
      "Given complete knowledge of a person’s genes, history, and environment, their choices may in principle be predictable.",
      "So-called universal values are more plausibly human constructions than objective features of the cosmos.",
      "Ageing, disease, and cognitive limitation are engineering problems, not sacred destinies that must be accepted.",
      "The universe’s deep mathematical structure gives serious grounds to consider reality as computation or simulation.",
      "I would rather bear the anxiety of freedom than inhabit a role named and defined for me by others.",
      "Even without a final end or guarantee, I remain willing to live and create with lucid awareness.",
      "I deliberately distinguish what lies within my control from what does not, lest emotion magnify reality without limit.",
      "A life without grand achievement, yet rich in love and tranquility, can still constitute a complete life.",
      "In evaluating an institution or technology, its capacity to reduce actual suffering matters more than its grandeur.",
      "Admitting “I do not know” is often epistemically wiser than arriving quickly at an elegant answer.",
      "Dreams, symbols, and subjective experience are not mere noise; they may disclose something about reality’s structure.",
      "If a claim can never be observed, tested, or make any discernible difference, I hesitate to regard it as knowledge.",
      "Understanding the causes behind behaviour matters more than merely praising or blaming an individual’s “will.”",
      "Once inherited meanings are dismantled, the remaining void is more honest than a consoling falsehood.",
      "With sufficient care, AI, brain–computer interfaces, and genetic technologies may carry consciousness into new forms.",
      "Even if the world is simulated, suffering, love, and choice retain real weight for consciousness within it.",
    ],
    clear: [
      "Life does not come with a script. I become who I am through the choices I make.",
      "Even if the universe never answers us, we can still live fully, clearly, and with humour.",
      "What matters most is not what happens to me, but how I understand it and respond.",
      "I would rather have friendship and peace than constantly chase stronger excitement.",
      "Even without believing in God, people can decide right from wrong by respecting and caring for one another.",
      "When someone offers a huge explanation, I first ask: what is the evidence, and what would prove it wrong?",
      "Consciousness may be more than something the brain produces; it might be a basic part of reality.",
      "Love, spirituality, and art can feel mysterious while still belonging to the natural world.",
      "If we knew everything about someone’s biology and life, we might be able to predict their choices.",
      "Values such as right and wrong seem created by humans, rather than written into the universe.",
      "Ageing, illness, and the limits of the mind are problems technology may solve—not a fate we must worship.",
      "Because the universe follows mathematics so closely, I seriously wonder whether reality is a computation or simulation.",
      "I would rather face the uncertainty of freedom than let other people decide who I must be.",
      "Even if my effort has no guaranteed ending, I still want to live, create, and keep going with open eyes.",
      "I try to separate what I can control from what I cannot, so my emotions do not make everything feel larger than it is.",
      "A quiet life with love and peace can be complete, even without fame or great achievement.",
      "A system or technology matters more for reducing real suffering than for looking impressive.",
      "Saying “I don’t know” is often wiser than rushing toward a beautiful answer.",
      "Dreams, symbols, and personal experiences are meaningful clues, not useless mental noise.",
      "If an idea can never be observed, tested, or change anything, I find it hard to call it knowledge.",
      "Understanding why people act as they do matters more than simply praising or blaming their willpower.",
      "An honest emptiness is better than a comforting meaning that I know is false.",
      "Used carefully, AI, brain interfaces, and gene technology could create entirely new forms of consciousness.",
      "Even in a simulated world, love, pain, and choice would still matter to anyone experiencing them.",
    ],
  },
  zh: {
    constellations: [
      "自由", "荒诞", "内在秩序", "愉悦", "尊严", "怀疑", "意识", "自然",
      "因果", "虚无", "进化", "现实", "真实", "反叛", "边界", "花园",
      "共同体", "未知", "梦境", "证据", "轨迹", "深渊", "未来", "界面",
    ],
    academic: [
      "人生没有预设剧本；我是谁，只能由一次次选择写出来。",
      "即使宇宙永远沉默，人仍可以清醒、热烈，甚至带着幽默活下去。",
      "真正重要的不是发生了什么，而是我如何判断并回应它。",
      "比起强烈刺激，我更向往友谊、宁静和不被欲望追赶的生活。",
      "没有神圣命令，人类的尊严与彼此的关怀依然足以成为伦理起点。",
      "面对宏大的解释，我首先会问：它有什么证据，又如何可能被证明是错的？",
      "意识不像物质的副产品；它也许是世界最基础的组成。",
      "爱、灵魂感与艺术再神秘，也终究发生在同一个自然世界里。",
      "如果知道一个人的全部基因、经历与环境，他的选择也许原则上可以被预测。",
      "所谓普遍价值更像人类的发明，而不是宇宙中客观存在的东西。",
      "衰老、疾病和认知极限是工程问题，不是必须接受的神圣命运。",
      "高度数学化的宇宙，让我认真怀疑现实可能是某种计算或模拟。",
      "我宁愿承担自由带来的焦虑，也不愿活成别人替我命名的角色。",
      "即使努力可能没有终点或保证，我仍愿意在清醒中继续生活与创造。",
      "我会主动区分可控与不可控，否则情绪就会把现实无限放大。",
      "一个没有宏大成就、却有爱与安宁的人生，也可以是完整的人生。",
      "衡量一种制度或技术时，它是否减少真实的人类痛苦比它是否宏伟更重要。",
      "承认“我不知道”常常比迅速得到一个漂亮答案更接近智慧。",
      "梦、象征与主观体验不是噪音，它们可能揭示现实本身的结构。",
      "如果某个说法永远无法观察、检验或产生差异，我很难把它当作知识。",
      "理解行为背后的原因，比单纯赞美或责怪一个人的“意志”更重要。",
      "当所有传统意义都被拆解，剩下的空白本身比虚假的安慰更诚实。",
      "只要足够谨慎，AI、脑机接口或基因技术可以让意识抵达全新的形态。",
      "即便世界是模拟，痛苦、爱与选择对身处其中的意识仍然具有分量。",
    ],
    clear: [
      "人生没有写好的剧本。我通过自己一次次的选择，成为现在的我。",
      "即使宇宙永远不给答案，人也可以清醒、热烈，甚至幽默地活着。",
      "最重要的不是发生了什么，而是我怎样理解它、怎样应对它。",
      "比起不停追求更强烈的刺激，我更想拥有友谊、平静和不被欲望追赶的生活。",
      "即使不相信神，人也可以因为尊重他人、关心彼此，而判断什么应该做、什么不应该做。",
      "听到一个解释整个世界的说法时，我会先问：证据是什么？怎样才能证明它错了？",
      "意识可能不只是大脑制造出来的东西，也可能是现实最基本的一部分。",
      "爱、灵魂感和艺术虽然很神秘，但仍然可以属于这个自然世界。",
      "如果我们知道一个人的身体和人生经历的全部信息，也许就能预测他的选择。",
      "善恶等普遍价值更像是人类创造出来的，而不是宇宙原本就写好的。",
      "衰老、疾病和思维能力的限制，是科技可能解决的问题，不是必须接受的命运。",
      "宇宙如此符合数学规律，让我认真怀疑现实会不会是一种计算或模拟。",
      "我宁愿面对自由选择的不安，也不愿让别人决定我必须成为谁。",
      "即使努力没有保证、也看不到终点，我仍愿意清醒地生活和创造。",
      "我会区分哪些事能控制、哪些不能，避免情绪把事情放大到失去边界。",
      "即使没有名望和伟大成就，只要拥有爱与平静，人生也可以是完整的。",
      "评价一种制度或技术时，它能否减少真实痛苦，比它看起来是否宏伟更重要。",
      "坦白说“我不知道”，常常比急着给出一个漂亮答案更有智慧。",
      "梦、象征和个人感受不是毫无用处的噪音，它们可能透露一些重要的东西。",
      "如果一种说法永远不能观察、检验，也不会产生任何区别，我很难把它叫作知识。",
      "理解一个人为什么这样做，比单纯夸奖或责怪他的意志力更重要。",
      "如果某种意义只是虚假的安慰，那么诚实地面对空白反而更好。",
      "只要足够谨慎，AI、脑机接口和基因技术可能创造全新的意识形态。",
      "即使世界是模拟出来的，身处其中的人感受到的爱、痛苦和选择仍然重要。",
    ],
  },
  fr: {
    constellations: [
      "Liberté", "Absurde", "Ordre intérieur", "Plaisir", "Dignité", "Doute",
      "Conscience", "Nature", "Causalité", "Néant", "Évolution", "Réalité",
      "Authenticité", "Révolte", "Limites", "Le jardin", "Communauté", "Inconnu",
      "Rêves", "Preuve", "Trajectoire", "Abîme", "Avenir", "Interface",
    ],
    academic: [
      "L’existence humaine n’obéit à aucun scénario prédéterminé ; mon identité se constitue à travers mes choix successifs.",
      "Même face au silence éternel de l’univers, on peut vivre avec lucidité, passion et même humour.",
      "L’essentiel n’est pas l’événement lui-même, mais le jugement que je porte sur lui et la réponse que je lui donne.",
      "Aux stimulations intenses, je préfère l’amitié, la tranquillité et une vie libérée de la tyrannie du désir.",
      "En l’absence de commandement sacré, la dignité humaine et la sollicitude réciproque suffisent encore à fonder l’éthique.",
      "Face à une explication totale, je demande d’abord quelles preuves l’étayent et ce qui pourrait la réfuter.",
      "La conscience n’est peut-être pas un simple sous-produit de la matière ; elle pourrait être une composante fondamentale du réel.",
      "Aussi mystérieux que soient l’amour, la spiritualité et l’art, ils se déploient toujours dans un même monde naturel.",
      "Une connaissance complète des gènes, de l’histoire et de l’environnement d’une personne rendrait peut-être ses choix prévisibles en principe.",
      "Les valeurs dites universelles semblent davantage être des constructions humaines que des propriétés objectives du cosmos.",
      "Le vieillissement, la maladie et les limites cognitives sont des problèmes d’ingénierie, non des destins sacrés à accepter.",
      "La structure profondément mathématique de l’univers justifie que l’on envisage sérieusement la réalité comme calcul ou simulation.",
      "Je préfère assumer l’angoisse de la liberté plutôt que d’habiter un rôle défini et nommé par autrui.",
      "Même sans terme final ni garantie, je demeure disposé à vivre et à créer dans la lucidité.",
      "Je distingue volontairement ce qui dépend de moi de ce qui n’en dépend pas, afin que l’émotion ne démesure pas le réel.",
      "Une vie sans accomplissement grandiose, mais riche d’amour et de tranquillité, peut néanmoins être complète.",
      "Pour juger une institution ou une technologie, sa capacité à réduire la souffrance réelle importe davantage que sa grandeur.",
      "Reconnaître « je ne sais pas » est souvent plus sage, sur le plan épistémique, que d’obtenir rapidement une réponse élégante.",
      "Les rêves, les symboles et l’expérience subjective ne sont pas de simples bruits ; ils peuvent dévoiler la structure du réel.",
      "Si une proposition ne peut jamais être observée, testée ni produire de différence, j’hésite à la considérer comme un savoir.",
      "Comprendre les causes d’un comportement importe davantage que louer ou blâmer la seule « volonté » d’un individu.",
      "Lorsque les significations héritées sont déconstruites, le vide qui demeure est plus honnête qu’une consolation mensongère.",
      "Avec une prudence suffisante, l’IA, les interfaces cerveau-machine et les technologies génétiques pourraient conduire la conscience vers de nouvelles formes.",
      "Même si le monde est simulé, la souffrance, l’amour et le choix conservent un poids réel pour la conscience qui l’habite.",
    ],
    clear: [
      "La vie n’a pas de scénario tout écrit. Je deviens qui je suis par les choix que je fais.",
      "Même si l’univers ne nous répond jamais, nous pouvons vivre pleinement, lucidement et avec humour.",
      "Le plus important n’est pas ce qui m’arrive, mais la manière dont je le comprends et dont j’y réponds.",
      "Je préfère l’amitié et la paix à la recherche constante de sensations plus fortes.",
      "Même sans croire en Dieu, on peut distinguer le bien du mal en respectant les autres et en prenant soin les uns des autres.",
      "Quand on me propose une grande explication, je demande d’abord : quelles sont les preuves, et qu’est-ce qui montrerait qu’elle est fausse ?",
      "La conscience est peut-être plus qu’un produit du cerveau ; elle pourrait être une partie fondamentale de la réalité.",
      "L’amour, la spiritualité et l’art peuvent sembler mystérieux tout en appartenant au monde naturel.",
      "Si nous savions tout de la biologie et de la vie d’une personne, nous pourrions peut-être prévoir ses choix.",
      "Le bien, le mal et les autres valeurs semblent créés par les humains plutôt qu’inscrits dans l’univers.",
      "Le vieillissement, la maladie et les limites de l’esprit sont peut-être des problèmes que la technologie peut résoudre, pas un destin à vénérer.",
      "Comme l’univers suit si bien les mathématiques, je me demande sérieusement si la réalité est un calcul ou une simulation.",
      "Je préfère affronter l’incertitude de la liberté plutôt que laisser les autres décider qui je dois être.",
      "Même si mes efforts n’ont aucune garantie, je veux continuer à vivre et à créer les yeux ouverts.",
      "J’essaie de séparer ce que je peux contrôler de ce que je ne peux pas, pour que mes émotions ne déforment pas tout.",
      "Une vie calme, pleine d’amour et de paix, peut être complète même sans gloire ni grand accomplissement.",
      "Un système ou une technologie compte davantage s’il réduit une souffrance réelle que s’il paraît impressionnant.",
      "Dire « je ne sais pas » est souvent plus sage que se précipiter vers une belle réponse.",
      "Les rêves, les symboles et les expériences personnelles sont des indices importants, pas un bruit inutile.",
      "Si une idée ne peut jamais être observée, testée ou changer quoi que ce soit, j’ai du mal à l’appeler un savoir.",
      "Comprendre pourquoi quelqu’un agit ainsi compte plus que simplement louer ou blâmer sa volonté.",
      "Un vide honnête vaut mieux qu’un sens réconfortant que je sais faux.",
      "Utilisées avec prudence, l’IA, les interfaces cérébrales et les technologies génétiques pourraient créer de nouvelles formes de conscience.",
      "Même dans un monde simulé, l’amour, la douleur et le choix compteraient toujours pour ceux qui les vivent.",
    ],
  },
};

export const ui = {
  en: {
    htmlLang: "en", headerMeta: "EN · 2026", home: "Back to home",
    eyebrow: "Not a label, but a constellation of consciousness",
    titleA: "Which philosophy", titleB: "are you?",
    intro: "24 propositions across freedom, absurdity, consciousness, causality, and reality. Discover the ideas that exert the strongest pull on you—and how they shape the way you understand the world.",
    languageHint: "LANGUAGE · 中文 / Français? Tap here to switch",
    versionLabel: "Choose your reading style",
    clearName: "Clear version", clearDesc: "Everyday language, direct and easy to understand",
    academicName: "Philosophical version", academicDesc: "Precise concepts and a more academic tone",
    start: "Enter the orbit", resume: (n: number) => `Continue from question ${n}`,
    minutes: "About 4 minutes", coordinates: "12 philosophical coordinates", shareable: "Shareable result",
    quote: "“Perhaps life has no answer sheet hidden deep in the universe, waiting for a clever mind to decode it.”",
    scroll: "SCROLL TO BEGIN · LOOK WITHIN", back: "← Back", coordinate: "Coordinate",
    instinct: "Answer with your first instinct",
    scale: ["Strongly disagree", "Disagree", "Unsure", "Agree", "Strongly agree"],
    answerAria: "Choose how much you agree", noCorrect: "There is no “correct” answer",
    footnote: "Your result describes the ideas pulling on you now—not a permanent identity.",
    primary: "Your philosophical primary star", readingTitle: "How your consciousness meets the world",
    light: "Light", shadow: "Shadow", ranking: "Philosophical gravity", dual: "Primary × secondary",
    dualSentence: (a: string, b: string, motto: string) => `Your centre is ${a}, yet ${b} also pulls on you. You believe “${motto.replace(/[.!?]/g, "")}”, while another coordinate keeps recalibrating you—contradiction is not a flaw, but evidence that consciousness has depth.`,
    corePrompt: "The central question you are answering",
    coreText: "It has no single correct answer. Every choice, creation, and act of persistence gradually gives shape to an answer of your own.",
    atlas: "Twelve philosophical coordinates",
    atlasLead: "This test reveals tendencies, not permanent labels. Open any philosophy to explore what it truly asks.",
    yourPrimary: "Your primary", what: "What it is", ideas: "Core ideas",
    misconception: "Common misconception", thinkers: "Thinkers and traditions",
    share: "Copy my consciousness coordinates", sent: "Coordinates sent into the universe",
    copied: "Copied to clipboard", retry: "Not copied—tap again", retake: "Travel through again",
    footer: "Meaning can be a provisional answer. You may rewrite it again and again as you grow.",
  },
  zh: {
    htmlLang: "zh-CN", headerMeta: "中文 · 2026", home: "回到首页",
    eyebrow: "不是标签，是一张意识星图", titleA: "你是哪种", titleB: "哲学主义？",
    intro: "24 个命题，穿过自由、荒诞、意识、因果与现实的底层。看看你最接近哪一种思想坐标，以及它如何影响你理解世界。",
    languageHint: "LANGUAGE · 点这里切换 English / Français",
    versionLabel: "选择题目表达方式",
    clearName: "通俗易懂版", clearDesc: "日常语言，直接清晰，一眼就能理解",
    academicName: "哲学论文版", academicDesc: "概念更精确，保留学术与哲思质感",
    start: "进入意识轨道", resume: (n: number) => `继续上次的第 ${n} 题`,
    minutes: "约 4 分钟", coordinates: "12 种思想坐标", shareable: "结果可分享",
    quote: "“人生也许没有一张埋在宇宙深处、等待聪明人解开的答卷。”",
    scroll: "SCROLL TO BEGIN · 向内凝视", back: "← 返回", coordinate: "坐标",
    instinct: "请凭第一直觉回答",
    scale: ["完全不认同", "不太认同", "难以决定", "比较认同", "非常认同"],
    answerAria: "选择认同程度", noCorrect: "没有“正确答案”",
    footnote: "你的结果描述的是此刻的思想引力，而不是永恒身份。",
    primary: "你的哲学主星", readingTitle: "你的意识如何面对世界",
    light: "光面", shadow: "暗面", ranking: "思想引力排行", dual: "主星 × 副星",
    dualSentence: (a: string, b: string, motto: string) => `你以${a}为核心，却也被${b}牵引。你既相信“${motto.replace(/[。！？]/g, "")}”，也会用另一套坐标校准自己——矛盾不是故障，而是意识拥有纵深的证据。`,
    corePrompt: "你正在回应的核心命题",
    coreText: "它没有唯一的标准答案。你每一次选择、创造和坚持，都在让属于你的答案逐渐成形。",
    atlas: "十二种哲学坐标", atlasLead: "测试给出的是思想倾向，不是永久标签。展开任意一种，了解它真正关心的问题。",
    yourPrimary: "你的主星", what: "它是什么", ideas: "核心观点",
    misconception: "常见误解", thinkers: "代表思想家与传统",
    share: "复制我的意识坐标", sent: "坐标已发送到宇宙",
    copied: "已复制到剪贴板", retry: "复制未完成，再点一次", retake: "重新穿越一次",
    footer: "意义可以是暂定答案。你可以在成长中，一次又一次重写它。",
  },
  fr: {
    htmlLang: "fr", headerMeta: "FR · 2026", home: "Retour à l’accueil",
    eyebrow: "Pas une étiquette, mais une constellation de conscience",
    titleA: "Quelle philosophie", titleB: "vous ressemble ?",
    intro: "24 propositions traversant la liberté, l’absurde, la conscience, la causalité et la réalité. Découvrez les idées qui exercent sur vous la plus forte attraction.",
    languageHint: "LANGUAGE · English / 中文 ? Touchez ici pour changer",
    versionLabel: "Choisissez le style des questions",
    clearName: "Version claire", clearDesc: "Des mots quotidiens, directs et faciles à comprendre",
    academicName: "Version philosophique", academicDesc: "Des concepts précis et un ton plus académique",
    start: "Entrer dans l’orbite", resume: (n: number) => `Reprendre à la question ${n}`,
    minutes: "Environ 4 minutes", coordinates: "12 coordonnées philosophiques", shareable: "Résultat partageable",
    quote: "« La vie n’a peut-être aucune réponse cachée au fond de l’univers, attendant d’être déchiffrée. »",
    scroll: "SCROLL TO BEGIN · REGARDEZ EN VOUS", back: "← Retour", coordinate: "Coordonnée",
    instinct: "Répondez selon votre première intuition",
    scale: ["Pas du tout d’accord", "Plutôt pas d’accord", "Indécis·e", "Plutôt d’accord", "Tout à fait d’accord"],
    answerAria: "Choisir votre degré d’accord", noCorrect: "Il n’existe pas de « bonne » réponse",
    footnote: "Votre résultat décrit l’attraction des idées aujourd’hui, pas une identité définitive.",
    primary: "Votre étoile philosophique principale", readingTitle: "Comment votre conscience rencontre le monde",
    light: "Lumière", shadow: "Ombre", ranking: "Gravité philosophique", dual: "Étoile principale × secondaire",
    dualSentence: (a: string, b: string, motto: string) => `Votre centre est ${a}, mais ${b} vous attire aussi. Vous croyez que « ${motto.replace(/[.!?]/g, "")} », tandis qu’une autre coordonnée vous recalibre : la contradiction n’est pas une faille, mais la profondeur de la conscience.`,
    corePrompt: "La question centrale à laquelle vous répondez",
    coreText: "Elle n’a pas de réponse unique. Chacun de vos choix, de vos actes créateurs et de vos élans persévérants donne peu à peu forme à votre propre réponse.",
    atlas: "Douze coordonnées philosophiques",
    atlasLead: "Ce test révèle des tendances, non des étiquettes permanentes. Ouvrez une philosophie pour découvrir sa véritable question.",
    yourPrimary: "Votre étoile", what: "Ce que c’est", ideas: "Idées essentielles",
    misconception: "Idée reçue", thinkers: "Penseurs et traditions",
    share: "Copier mes coordonnées de conscience", sent: "Coordonnées envoyées dans l’univers",
    copied: "Copié dans le presse-papiers", retry: "Échec de la copie — réessayez", retake: "Refaire le voyage",
    footer: "Le sens peut être une réponse provisoire. Vous pouvez le réécrire encore et encore en grandissant.",
  },
};
